a = 10
b = 3
print ("a =", a)
print("b = ", b)
print("a + b = ", a+b)
print("a - b = ", a-b)
print("a * b = ", a*b)
print("a / b = ", a/b)
print("a % b = ", a%b) #reminder
print("a ** b = ", a**b) #power
print("a // b = ", a//b) #floor devision
